spring.application.name=financeTracker
spring.data.mongodb.uri=mongodb+srv://Nirmay:Niru2002@cluster0.eylkrsv.mongodb.net/NPS?retryWrites=true&w=majority&appName=Cluster0
server.port=3000

jwt.secret=d3c7546cc643e7b65132af0673460fbd836c477ebad4822f95b74d5a2791154b
jwt.expiration=86400000